# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11FhtONA4j_zzjA8-xhmGiiRDBdS8QEHw
"""

#!/usr/bin/env python
# coding: utf-8

import streamlit as st
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

# Load dataset
bike_data = pd.read_csv("day.csv")

# Map weather and season data
weather = {
    1: "Clear",
    2: "Mist",
    3: "Light Rain",
    4: "Heavy Rain"
}

season = {
    1: "Spring",
    2: "Summer",
    3: "Fall",
    4: "Winter"
}

bike_data["weather"] = bike_data["weathersit"].map(weather)
bike_data["season"] = bike_data["season"].map(season)

# Sidebar navigation
st.sidebar.title("Bike Rental Analysis")
sections = ["Overview", "Rentals by Weather", "Rentals by Season and Hour"]
selected_section = st.sidebar.radio("Select Analysis", sections)

# Overview section
if selected_section == "Overview":
    st.header("Overview of Bike Rental Data")
    st.write("This dashboard provides insights into bike rentals based on weather, season, day, and hour.")
    st.dataframe(bike_data)

# Rentals by Weather
if selected_section == "Rentals by Weather":
    st.subheader("Bike Rentals Based on Weather Conditions")

    # Select weather condition
    selected_weather = st.selectbox("Select Weather Condition:", bike_data['weather'].unique())

    filtered_data = bike_data[bike_data["weather"] == selected_weather]

    # Average rentals by weather condition
    avg_rentals = filtered_data["cnt"].mean()
    st.write(f"**Average Rentals during '{selected_weather}' Condition:** {avg_rentals:.2f}")

    # Bar plot of rentals by weather
    fig, ax = plt.subplots(figsize=(8, 6))
    sns.barplot(x="weather", y="cnt", data=filtered_data, palette="coolwarm", ax=ax)
    ax.set_title(f"Rentals During '{selected_weather}' Weather Condition", fontsize=14)
    ax.set_ylabel("Number of Rentals")
    st.pyplot(fig)

# Rentals by Season and Hour
if selected_section == "Rentals by Season and Hour":
    st.subheader("Bike Rentals by Season and Hour")

    # Select season and hour
    selected_season = st.selectbox("Select Season:", bike_data['season'].unique())
    selected_hour = st.slider("Select Hour of the Day (0-23):", 0, 23, 12)

    # Filter data by season and hour
    filtered_data = bike_data[(bike_data["season"] == selected_season) & (bike_data["hr"] == selected_hour)]

    avg_rentals_by_hour = filtered_data["cnt"].mean()
    st.write(f"**Average Rentals in {selected_season} at {selected_hour}:00:** {avg_rentals_by_hour:.2f}")

    # Line plot of rentals by hour for the selected season
    fig, ax = plt.subplots(figsize=(8, 6))
    sns.lineplot(x="hr", y="cnt", data=bike_data[bike_data["season"] == selected_season], ax=ax, marker="o")
    ax.set_title(f"Rentals by Hour in {selected_season}", fontsize=14)
    ax.set_xlabel("Hour of the Day")
    ax.set_ylabel("Number of Rentals")
    st.pyplot(fig)

# Footer
st.sidebar.caption("Bike Rental Dashboard by Andreansyah Budi")
st.caption("Data from Capital Bikeshare - Washington D.C.")

pip install streamlit